### ISSUE TITLE
TypeError: feature.getFailureException is not a function

### ISSUE THREAD

**Issue by ALeo23** [webdriverio/wdio-sauce-service#44]
Hello,

I'm getting this error when running the tests using wdio, even after updating to 0.4.4:

TypeError: feature.getFailureException is not a function
    at SauceService.afterStep (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sauce-service/build/sauce-service.js:94:53)
    at execHook (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sync/build/index.js:166:35)

There is a similar fix on wdio-browserstack-service package, see https://github.com/itszero/wdio-browserstack-service/pull/13 however, it's been implemented differently in wdio-sauce-service. I am still hitting this issue after the previous PR was merged, so it looks like the issue may still exist.

Best regards,
Alex

**Comment by ALeo23** [comment]
Thanks a lot for the quick fix!

**Comment by froucher** [comment]
Sorry, if I am not mistaken, then I think last version has not be built with the following fix https://github.com/webdriverio/wdio-sauce-service/commit/4c15700e8f383d2a616ed622d40fac025d7da9c7.

I just install last version in new folder as you can see with the following commands:

```
$ cat package.json                     
{
  "name": "test",
  "license": "ISC",
  "dependencies": {
    "wdio-sauce-service": "^0.4.7"
  }
}
$ npm list                             
test@1.0.0 /Users/feliperoucheriglesias/salesforce/test
└─┬ wdio-sauce-service@0.4.7
...
```

But lines are not like last commit https://github.com/webdriverio/wdio-sauce-service/commit/4c15700e8f383d2a616ed622d40fac025d7da9c7

```
$ cat -n node_modules/wdio-sauce-service/build/sauce-service.js | sed '93,95!d'
    93	        value: function afterStep(feature) {
    94	            if (feature.failureException || feature.getFailureException()) {
    95	                ++this.failures;
```

The expected code should be like:

```
    93	        value: function afterStep(feature) {
    94	            if (feature.failureException ||  (typeof feature.getFailureException === 'function' && feature.getFailureException()) {
    95	                ++this.failures;
```

**Comment by schmalzs** [comment]
Seeing the same thing. Has there been a release since this fix was added in?

**Comment by christian-bromann** [comment]
I just rereleased the package. I think something was borked with the release script

**Comment by robhowell** [comment]
@christian-bromann I'm still seeing the same issue - after installing version 0.4.7 from npm I'm still seeing the error and seeing the old version of the afterStep function in `build/sauce-service.js`:

```
      key: 'afterStep',
        value: function afterStep(feature) {
            if (feature.failureException || feature.getFailureException()) {
                ++this.failures;
            }
        }
```

For reference, here's a link to that file in the built version of 0.4.7 on unpkg.com so that you can verify that it still has the old version of afterStep(): https://unpkg.com/wdio-sauce-service@0.4.7/build/sauce-service.js
