### PR TITLE
fix: Add null check to getFailureException call

### LINKED ISSUE #44: TypeError: feature.getFailureException is not a function
Hello,

I'm getting this error when running the tests using wdio, even after updating to 0.4.4:

TypeError: feature.getFailureException is not a function
    at SauceService.afterStep (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sauce-service/build/sauce-service.js:94:53)
    at execHook (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sync/build/index.js:166:35)

There is a similar fix on wdio-browserstack-service package, see https://github.com/itszero/wdio-browserstack-service/pull/13 however, it's been implemented differently in wdio-sauce-service. I am still hitting this issue after the previous PR was merged, so it looks like the issue may still exist.

Best regards,
Alex

### PR DESCRIPTION
**Pull request by mDalessandro**
Closes #44

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Happy to merge this once CLA is signed

**Comment by mDalessandro** [comment]
Hello! I've accepted the Contributor License Agreement.

**Comment by christian-bromann** [comment]
It still says `Contributor License Agreement is not signed yet.` .. did you signed it with the right email address?

**Comment by mDalessandro** [comment]
For the CLA, I used the email address associated with my github, but I think there is a different email associated with the commit. I can't edit the CLA anymore.

Edit: I've added the email associated with the commit to my github account, as the instructions above mention. Do I need to resign the CLA with the commit email?

**Comment by christian-bromann** [comment]
> Do I need to resign the CLA with the commit email?

Yes, feel free to just create a new PR
