### PR TITLE
fix: Add null check to getFailureException call

### LINKED ISSUE #44: TypeError: feature.getFailureException is not a function
Hello,

I'm getting this error when running the tests using wdio, even after updating to 0.4.4:

TypeError: feature.getFailureException is not a function
    at SauceService.afterStep (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sauce-service/build/sauce-service.js:94:53)
    at execHook (/Users/aleo23/Documents/motorcycle/moto-web/node_modules/wdio-sync/build/index.js:166:35)

There is a similar fix on wdio-browserstack-service package, see https://github.com/itszero/wdio-browserstack-service/pull/13 however, it's been implemented differently in wdio-sauce-service. I am still hitting this issue after the previous PR was merged, so it looks like the issue may still exist.

Best regards,
Alex

### PR DESCRIPTION
**Pull request by mDalessandro**
Closes #44

### CODE REVIEW

**Comment by mDalessandro** [comment]
The CLA doesn't give the option to resign.

**Comment by christian-bromann** [comment]
Released in v0.4.6
